
fun listp(Absyn.EMPTY)=[]
	|listp(Absyn.PR(a,b))=app(lists(a),listp(b))
and lists(Absyn.FT(f))=listf(f)
	|lists(Absyn.RL(r))=listr(r)
and listf(Absyn.LT(l))=listl(l)
and listr(Absyn.HB(h,b))=app(listh(h),listb(b))
and listh(Absyn.HD(h))=listl(h)
and listb(Absyn.BD(l))=listl(l)
	|listb(Absyn.LB(l,b))=app(listl(l),listb(b))
and listl(Absyn.LNM(n))=[]
	|listl(Absyn.LNT(n,t))=listt(t)
and listt(Absyn.TU(t))=listlt(t)
and listlt(Absyn.L1(t))=listtm(t)
	|listlt(Absyn.L2(t,lt))=app(listtm(t),listlt(lt))
and listtm(Absyn.T1(n))=[]
	|listtm(Absyn.T2(v))=v::[]
	|listtm(Absyn.T3(n,t))=listt(t)
and app(a,b)  = a@b;
