
fun sizep(Absyn.EMPTY)=0
	|sizep(Absyn.PR(a,b))=1+add(sizes(a),sizep(b))
and sizes(Absyn.FT(f))=1+sizef(f)
	|sizes(Absyn.RL(r))=1+sizer(r)
and sizef(Absyn.LT(l))=1+sizel(l)
and sizer(Absyn.HB(h,b))=1+add(sizeh(h),sizeb(b))
and sizeh(Absyn.HD(h))=1+sizel(h)
and sizeb(Absyn.BD(l))=1+sizel(l)
	|sizeb(Absyn.LB(l,b))=1+add(sizel(l),sizeb(b))
and sizel(Absyn.LNM(n))=2
	|sizel(Absyn.LNT(n,t))=2+sizet(t)
and sizet(Absyn.TU(t))=1+sizelt(t)
and sizelt(Absyn.L1(t))=1+sizetm(t)
	|sizelt(Absyn.L2(t,lt))=1+add(sizetm(t),sizelt(lt))
and sizetm(Absyn.T1(n))=2
	|sizetm(Absyn.T2(v))=2
	|sizetm(Absyn.T3(n,t))=2+sizet(t)
and add(a,b)  = a+b;
